# Mark Shust's Docker Configuration for Magento (https://github.com/markoshust/docker-magento)
# Version 13.0.0

version: "3"

services:
  app:
    image: markoshust/magento-nginx:1.13-3
    networks:
      - magento
    volumes: &appvolumes
      - ./src:/var/www/html:delegated
      - ~/.composer:/var/www/html/var/composer_home:delegated
      - ~/.composer:/var/www/.composer:delegated
      - sockdata:/sock

  phpfpm:
    image: 999games/magento-php:7.0-fpm-2
    networks:
      - magento
    volumes: *appvolumes

  cron:
    image: markoshust/magento-php:7.0-fpm-2
    user: root
    command: /usr/local/bin/cronstart
    tty: true
    networks:
      - magento
    volumes: *appvolumes

  db:
    image: percona:5.7
    networks:
      - magento
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
  sockdata:

networks:
  magento:
    driver: overlay