# Mark Shust's Docker Configuration for Magento (https://github.com/markoshust/docker-magento)
# Version 13.0.0

version: "3"

services:
  app:
    image: markoshust/magento-nginx:1.13-3
    networks:
      - magento
    volumes: &appvolumes
      - /var/www/html:/var/www/html:delegated
      - /var/www/composer:/var/www/html/var/composer_home:delegated
      - /var/www/composer:/var/www/.composer:delegated
      - sockdata:/sock
    deploy:
      replicas: 1
    ports:
      - 80:80
      - 443:443

  phpfpm:
    image: 999games/magento-php:7.0-fpm-2
    networks:
      - magento
    volumes: *appvolumes
    deploy:
      replicas: 1

  cron:
    image: 999games/magento-php:7.0-fpm-2
    user: root
    command: /usr/local/bin/cronstart
    tty: true
    networks:
      - magento
    volumes: *appvolumes
    deploy:
      replicas: 1

volumes:
  sockdata:

networks:
  magento:
    driver: overlay